### ISSUE TITLE
Litmus-Docs links from Google Search Results redirecting to old broken links

### ISSUE THREAD

**Issue by Lucifergene** [litmuschaos/litmus-docs#117]
##  BUG REPORT
 

**What happened**:

Google search for Litmus Version 1 docs lead to pages that gives a status code of 404.

The issue is caused due to the change in the URL of the Litmus v1 documentation.

Google Search Result: https://docs.litmuschaos.io/docs/1.7.0/openshift-litmus/ (404 error)

Corrected Link found on browsing the Docs: https://v1-docs.litmuschaos.io/docs/1.7.0/openshift-litmus/ (Working)

**What you expected to happen**:

There should be a redirection from the older URL to the newer URL.

**How to reproduce it (as minimally and precisely as possible)**:

 - Perform a Google Search: `litmus chaos openshift`
 - Selecting the First Search Result

**Comment by mehabhalodiya** [comment]
Hey, where to modify this?
I would like to contribute.

**Comment by Jonsy13** [comment]
Hi @mehabhalodiya @Lucifergene , This issue has been resolved now. You may find one link from netlify that will also be reindexed & removed by google in sometime. Closing this issue for now, feel free to open it again if issues persists. Thankyou!
