### ISSUE TITLE
Broken Edit Page option redirects to wrong source page.

### ISSUE THREAD

**Issue by PratikBorhade302** [litmuschaos/litmus-docs#120]
**What happened**:
`Edit Page` option redirects to the wrong GitHub source page (which results to an error 404)

**What you expected to happen**:
Should open a correct GitHub source page.

**How to reproduce it (as minimally and precisely as possible)**:
- Open [what-is-litmus](https://docs.litmuschaos.io/docs/introduction/what-is-litmus)
- Scroll down to the bottom of the page
- Click on `Edit Page`
- Should redirect to [GitHub](https://github.com/litmuschaos/litmus-docs/blob/master/website/docs/introduction/what-is-litmus.md) page (Instead it opens [wrong source page](https://github.com/litmuschaos/litmus-docs/edit/staging/website/versioned_docs/version-2.0.0/introduction/what-is-litmus.md))

**Comment by PratikBorhade302** [comment]
Hi, I would like to fix this but before that let me know if this would be considered as a valid report :)

**Comment by Jonsy13** [comment]
Hi @PratikBorhade302 , can you please check, this is just fixed. The staging branch wasn't synced to master. We have synced it.

**Comment by PratikBorhade302** [comment]
Hi, yes. This is fixed now. Thanks for the quick fix btw ;)

Will close the report.
