### ISSUE TITLE
Search in the doc is not working.

### ISSUE THREAD

**Issue by aryan-bhokare** [litmuschaos/litmus-docs#247]
## Is this a BUG REPORT or FEATURE REQUEST?
 
BUG REPORT

**What happened**:
The search in the docs shows nothing even if we search keywords present in the docs.

**What you expected to happen**:
The search results according to the keyword.

**How to reproduce it (as minimally and precisely as possible)**:
![Screenshot from 2024-01-30 12-30-19](https://github.com/litmuschaos/litmus-docs/assets/92683836/4eb58156-9fd7-4aa8-ac9b-1db8eb0669f2)
![Screenshot from 2024-01-30 12-29-48](https://github.com/litmuschaos/litmus-docs/assets/92683836/a6b9c0d6-685b-4155-a257-a86f30eb9ce1)

**Comment by kartikaysaxena** [comment]
I want to work on this

**Comment by prithvi1307** [comment]
@kartikaysaxena let's close the issues you have taken one by one and you can pick this then

**Comment by neelanjan00** [comment]
Hi @kartikaysaxena were you able to work on this?

**Comment by Jonsy13** [comment]
This has been fixed now! Closing this issue.
