### ISSUE TITLE
Move contributor info out of intro

### ISSUE THREAD

**Issue by dwelsch-esi** [litmuschaos/litmus-docs#299]
## FEATURE REQUEST: Move contributor info out of doc intro

Move "How to Contribute" out of the ["What is Litmus"](https://docs.litmuschaos.io/docs/introduction/what-is-litmus) page. "What is Litmus" is introductory conceptual material; "How to Contribute" is advanced instructional information for a different audience. 

### Context

This issue tracks recommended changes resulting from an analysis of the Litmus Chaos
documentation commissioned by CNCF. The analysis and supporting documents are
here: <https://github.com/cncf/techdocs/tree/main/analyses> under `0013-litmuschaos`.

### Possible Implementation

Remove "How to Contribute" from the ["What is Litmus"](https://docs.litmuschaos.io/docs/introduction/what-is-litmus) page. Move it to the [Community](https://docs.litmuschaos.io/docs/introduction/community) page, under or near the "Contribute" section.

**Comment by andoriyaprashant** [comment]
Hi @hrishavjha @SarthakJain26  I would like to work on this issue. Please let me know if I can proceed
Thank you
